# Extremesealevel2 Points-Over-Threshold pipeline configuration

Fit:
  task1:
    executable: "python3"
    python_dependencies]: "numpy pandas xarray os scipy"
    script: "extremesealevel2_AFs_fit.py"
    options:
      - "minYears"
      - "resample_freq"
      - "deseasonalize"
      - "detrend"
      - "subtract_amean"
      - "match_lim"
      - "gpd_pot_threshold"
      - "decluster_window"
      - "decluster_method"
      - "nsamps"
      - "total_local_sl_file"
      - "esl_data"
      - "esl_data_path"
      - "pipeline_id"
    upload_input_data:
      - 'projectESL/esl_analysis.py'
      - 'projectESL/I_O.py'