apiVersion: v1
kind: Pod

metadata:
  name: test

spec:
  volumes:
    # - name: fairtest-hostdir
    #   hostPath:
    #     path: homedir/Capstone/facts/fairtest
    - name: fittedismiptest-hostdir
      hostPath:
        path: homedir/Capstone/facts/fittedismiptest
    - name: larmiptest-hostdir
      hostPath:
        path: homedir/Capstone/facts/larmiptest
    # - name: tlmtest-hostdir
    #   hostPath:
    #     path: homedir/Capstone/facts/tlmtest
    - name: totaltest-hostdir
      hostPath:
        path: homedir/Capstone/facts/totaltest
    - name: shared-data-hostdir
      hostPath:
        path: homedir/Capstone/facts/totaltest/to_total

  initContainers:
    # - name: fairtest-container
    #   image: factscapstone/facts:fairtest
    #   imagePullPolicy: Always
    #   workingDir: /opt/fairtest
    #   command: ["/bin/sh", "execute.sh"]
    #   volumeMounts:
    #     - name: fairtest-hostdir
    #       mountPath: /opt/fairtest
    #     - name: shared-data-hostdir
    #       mountPath: /opt/shared_data
    - name: fittedismiptest-container
      image: factscapstone/facts:fittedismiptest
      imagePullPolicy: Always
      workingDir: /opt/fittedismiptest
      command: ["/bin/sh", "execute.sh"]
      volumeMounts:
        - name: fittedismiptest-hostdir
          mountPath: /opt/fittedismiptest
        - name: shared-data-hostdir
          mountPath: /opt/shared_data
    - name: larmiptest-container
      image: factscapstone/facts:larmiptest
      imagePullPolicy: Always
      workingDir: /opt/larmiptest
      command: ["/bin/sh", "execute.sh"]
      volumeMounts:
        - name: larmiptest-hostdir
          mountPath: /opt/larmiptest
        - name: shared-data-hostdir
          mountPath: /opt/shared_data
    # - name: tlmtest-container
    #   image: factscapstone/facts:tlmtest
    #   imagePullPolicy: Always
    #   workingDir: /opt/tlmtest
    #   command: ["/bin/sh", "execute.sh"]
    #   volumeMounts:
    #     - name: tlmtest-hostdir
    #       mountPath: /opt/tlmtest
  containers:
    - name: totaltest-container
      image: factscapstone/facts:totaltest
      imagePullPolicy: Always
      workingDir: /opt/totaltest
      command: ["/bin/sh", "execute.sh"]
      volumeMounts:
        - name: totaltest-hostdir
          mountPath: /opt/totaltest
        - name: shared-data-hostdir
          mountPath: /opt/to_total

  restartPolicy: OnFailure
