apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"  # Replace with actual host directory path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: fittedismiptest
    image: fittedismiptest
    imagePullPolicy: Never
    command: 
      - "/bin/sh"
      - "-c"
      - "sleep 3600"
    volumeMounts: 
      - name: data-volume
        mountPath: "/opt/shared_data"
  - name: larmiptest
    image: larmiptest
    imagePullPolicy: Never
    command: 
      - "/bin/sh"
      - "-c"
      - "sleep 3600"
    volumeMounts: 
      - name: data-volume
        mountPath: "/opt/shared_data"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc
  restartPolicy: OnFailure

---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: total-pod
# spec:
#   containers:
#   - name: totaltest
#     image: totaltest
#     imagePullPolicy: Never
#     command: 
#       - "/bin/sh"
#       - "-c"
#       - "sleep 3600"
#     volumeMounts: 
#       - name: data-volume
#         mountPath: "/opt/shared_data"
#   volumes:
#     - name: data-volume
#       persistentVolumeClaim:
#         claimName: my-pvc
#   restartPolicy: OnFailure

