apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: fittedismiptest
    image: fittedismiptest
    imagePullPolicy: Never
    command: 
      - "/bin/sh"
      - "-c"
      - "sh execute.sh"
    volumeMounts: 
      - name: data-volume
        mountPath: "/opt/shared_data"
  - name: larmiptest
    image: larmiptest
    imagePullPolicy: Never
    command: 
      - "/bin/sh"
      - "-c"
      - "sh execute.sh"
    volumeMounts: 
      - name: data-volume
        mountPath: "/opt/shared_data"
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: my-pvc
  restartPolicy: OnFailure
