apiVersion: v1
kind: Pod

metadata:
  name: test-run

spec:
  volumes:
    - name: total-data-volume
      persistentVolumeClaim:
        claimName: total-data-pvc
    - name: output-data-volume
      persistentVolumeClaim:
        claimName: output-data-pvc

  containers:
    - name: test
      image: ubuntu
      imagePullPolicy: Never
      command:
        - "/bin/bash"
        - "-c"
        - "sleep infinity"
      volumeMounts:
        - name: total-data-volume
          mountPath: "/opt/total_data"
        - name: output-data-volume
          mountPath: "/opt/output_data"

  restartPolicy: Never
